config/routes.rb
Rails.application.routes.draw do
  scope module: 'admin', path: '/admin', as: 'admin' do
    resources :users
    resources :projects
    resources :components
    get '', to: 'users#index'
  end

  scope '/(:locale)', locale: /en|ru/ do
    resources :users, only: [:index, :show] do
      resources :projects, only: [:index]
    end
    resources :projects, only: [:show]
    resources :comments, only: [:index, :new, :create], default: {format: :json}

    root 'users#index'
  end

  match '*path' => redirect { |p, req| req.flash[:alert] = 'Aaargh, this path is not exist'; '/' }, via: [:get, :post]
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :components, through: :component_projects
  has_many :component_projects, dependent: :destroy
  has_and_belongs_to_many :users
  # has_many :project_users, dependent: :destroy
  has_many :images, dependent: :destroy
  has_many :notifies, as: :notifiable

  validates :name, :info_en, :info_ru, presence: true
  validates :order_pos, presence: true, numericality: true

  accepts_nested_attributes_for :component_projects, allow_destroy: true
  accepts_nested_attributes_for :images, allow_destroy: true

  def info
    send("info_#{I18n.locale}").to_s
  end

  def as_json(options = {})
    { image_url: images.first.try(:url) || PictureUploader.default_url, id: id, name: name }
  end
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::AdminController

  before_filter :find_project, except: [:index, :new, :create]

  def index
    respond_to do |mime|
      mime.html
      mime.json { render json: { projects: Project.all.as_json } }
    end
  end

  def show; end

  def new; end

  def create
    @project = Project.create(project_params)
    if @project.persisted?
      redirect_to [:admin, :projects]
    else
      render 'admin/projects/_form'
    end
  end

  def edit; end

  def update
    if @project.update_attributes(project_params)
      redirect_to [:admin, @project]
    else
      render 'admin/projects/_form'
    end
  end

  def destroy
    @project.destroy
    if @project.destroyed?
      redirect_to [:admin, :projects]
    else
      redirect_to [:admin, :projects], alert: 'Error!'
    end
  end

  private

  def find_project
    @project = Project.find_by(id: params[:id].to_i)
  end

  def project_params
    params.require(:project).permit(
      :name, :company,
      :info_ru, :info_en, :order_pos,
      component_projects_attributes: [:id, :project_id, :component_id, :_destroy],
      images_attributes: [:id, :path, :_destroy]
    )
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :find_user, only: :index

  def index
    @projects = pagination(@user.projects.order(:order_pos), params[:page])
  end

  def show
    @project = Project.find_by(id: params[:id].to_i)
    @components = @project.components.group_by(&:type_name)
  end

  private

  def find_user
    redirect_to :root unless (@user = User.find_by(id: params[:user_id].to_i))
  end
end

app/helpers/admin/projects_helper.rb
module Admin::ProjectsHelper

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/admin/projects/_form.html.slim
= render layout: 'shared/modal', locals: {title: 'Create component dialog', modal_id: 'componentModal'} do
    = render 'admin/components/form'

= nested_form_for [:admin, @project || Project.new], multipart: true do |f|
  = render 'shared/form_errors', form_errors: f.object

  /= image_tag f.object.avatar.url(:thumbnail)
  /
  /.row
  /  = f.hidden_field :avatar_cache
  /  = f.file_field :avatar
  .form-group.row
    .col-xs-9
      = f.label :name
      = f.text_field :name, class: 'form-control'
    .col-xs-3
      = f.label :order_pos
      = f.text_field :order_pos, class: 'form-control integer'

  .form-group
    = f.label :company
    = f.text_field :company, class: 'form-control'

  .form-group.row
    .col-xs-6
      = f.label :info_en
      = f.text_area :info_en, class: 'form-control tinymce'
      = tinymce_assets
      = tinymce
    .col-xs-6
      = f.label :info_ru
      = f.text_area :info_ru, class: 'form-control tinymce'
      = tinymce_assets
      = tinymce


  .form-group
    = f.label 'Components'
    /button.btn.btn-default data-target="#componentModal" data-toggle="modal" type="button"
    = f.fields_for :component_projects do |cp|
      = cp.collection_select :component_id, Component.order(:name), :id, :name, {}, class: 'componentsList'
      = cp.link_to_remove 'Remove this component', class: 'btn btn-danger'

    div
      = f.link_to_add 'Add a component', :component_projects, class: 'btn btn-success'
      = link_to 'Create new component', '#', class: 'btn btn-info', data: {target:'#componentModal', toggle: 'modal'}

  .form-group
    = f.fields_for :images do |img|
      = image_tag img.object.path.url(:thumbnail)
      = img.hidden_field :path_cache
      = img.file_field :path
      = img.link_to_remove 'Remove this image', class: 'btn btn-danger'
    = f.link_to_add 'Add an image', :images, class: 'btn btn-success'

  = f.button type: :submit, class: 'btn btn-default'

app/views/admin/projects/_project.html.slim
.row data-ng-repeat="project in projects track by $index"
  .col-md-4
    img data-ng-src="{{ project.image_url }}" src=''
  .col-md-8
    = link_to '{{ project.name }}', ng_link(edit_admin_project_path(id: '{{ project.id }}')), class: 'v-align'

app/views/admin/projects/edit.html.slim
h1
 | Editing of the project: #{@project.name}
= render 'admin/projects/form'

app/views/admin/projects/index.html.slim
div data-ng-controller="projectsCtrl"
  = render 'admin/projects/project'

app/views/admin/projects/new.html.slim
h1 New project
= render 'admin/projects/form'

app/views/admin/projects/show.html.slim
h1 Project: #{@project.name}
p Company: #{@project.company}
hr
p Info en: #{@project.info_en.html_safe}
p Info ru: #{@project.info_ru.html_safe}