config/routes.rb
Rails.application.routes.draw do
  scope module: 'admin', path: '/admin', as: 'admin' do
    resources :users
    resources :projects
    resources :components
    get '', to: 'users#index'
  end

  scope '/(:locale)', locale: /en|ru/ do
    resources :users, only: [:index, :show] do
      resources :projects, only: [:index]
    end
    resources :projects, only: [:show]
    resources :comments, only: [:index, :new, :create], default: {format: :json}

    root 'users#index'
  end

  match '*path' => redirect { |p, req| req.flash[:alert] = 'Aaargh, this path is not exist'; '/' }, via: [:get, :post]
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :components, through: :component_projects
  has_many :component_projects, dependent: :destroy
  has_and_belongs_to_many :users
  # has_many :project_users, dependent: :destroy
  has_many :images, dependent: :destroy
  has_many :notifies, as: :notifiable

  validates :name, :info_en, :info_ru, presence: true
  validates :order_pos, presence: true, numericality: true

  accepts_nested_attributes_for :component_projects, allow_destroy: true
  accepts_nested_attributes_for :images, allow_destroy: true

  def info
    send("info_#{I18n.locale}").to_s
  end

  def as_json(options = {})
    { image_url: images.first.try(:url) || PictureUploader.default_url, id: id, name: name }
  end
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::AdminController

  before_filter :find_project, except: [:index, :new, :create]

  def index
    respond_to do |mime|
      mime.html
      mime.json { render json: { projects: Project.all.as_json } }
    end
  end

  def show; end

  def new; end

  def create
    @project = Project.create(project_params)
    if @project.persisted?
      redirect_to [:admin, :projects]
    else
      render 'admin/projects/_form'
    end
  end

  def edit; end

  def update
    if @project.update_attributes(project_params)
      redirect_to [:admin, @project]
    else
      render 'admin/projects/_form'
    end
  end

  def destroy
    @project.destroy
    if @project.destroyed?
      redirect_to [:admin, :projects]
    else
      redirect_to [:admin, :projects], alert: 'Error!'
    end
  end

  private

  def find_project
    @project = Project.find_by(id: params[:id].to_i)
  end

  def project_params
    params.require(:project).permit(
      :name, :company,
      :info_ru, :info_en, :order_pos,
      component_projects_attributes: [:id, :project_id, :component_id, :_destroy],
      images_attributes: [:id, :path, :_destroy]
    )
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :find_user, only: :index

  def index
    @projects = pagination(@user.projects.order(:order_pos), params[:page])
  end

  def show
    @project = Project.find_by(id: params[:id].to_i)
    @components = @project.components.group_by(&:type_name)
  end

  private

  def find_user
    redirect_to :root unless (@user = User.find_by(id: params[:user_id].to_i))
  end
end

app/helpers/admin/projects_helper.rb
module Admin::ProjectsHelper

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_project.html.slim
.project
  .row
    .col-xs-12.col-sm-7.col-sm-push-5
      h3= project.name
      h4= project.company
      p== project.info
      = link_to 'View Project', project_path(project), class: 'btn btn-primary'
    .col-xs-12.col-sm-5.col-sm-pull-7
      = render partial: 'shared/gallery', locals: {images: project.images}
  hr

app/views/projects/index.html.slim
.container
  .row
    .col-lg-12
      .fix-size.centered= image_tag 'AjaxLoader.gif', class: 'img-circle img-responsive centered async_img', data: {src: @user.avatar_url}
      h1.text-center
        = @user.full_name
      .text-center
        = raw(@user.info)
      h2.page-header.text-center
        = t('projects.page_title', name: @user.full_name)
  .projects_block
    = render @projects

  = paginate @projects

app/views/projects/show.html.slim
h1 Project #{@project.name} (#{@project.company})

hr
= @project.info.html_safe
hr

.row
  .col-xs-12.col-sm-6.images
    - @project.images.each do |image|
      = link_to '#', class: 'img_clc', data: {url: image.path.url} do
        = image_tag image.path.standard.url

  .col-xs-12.col-sm-6.components
    - @components.each do |name, collection|
      .pad_left
        b #{name}:
        .pad_left
          = render collection