config/routes.rb
Rails.application.routes.draw do
  scope module: 'admin', path: '/admin', as: 'admin' do
    resources :users
    resources :projects
    resources :components
    get '', to: 'users#index'
  end

  scope '/(:locale)', locale: /en|ru/ do
    resources :users, only: [:index, :show] do
      resources :projects, only: [:index]
    end
    resources :projects, only: [:show]
    resources :comments, only: [:index, :new, :create], default: {format: :json}

    root 'users#index'
  end

  match '*path' => redirect { |p, req| req.flash[:alert] = 'Aaargh, this path is not exist'; '/' }, via: [:get, :post]
end

app/models/user.rb
class User < ActiveRecord::Base
  mount_uploader :avatar, ::PictureUploader

  has_and_belongs_to_many :projects#, through: :project_users
  # has_many :project_users, dependent: :destroy
  has_many :user_links, dependent: :destroy
  has_many :notifies, as: :notifiable

  has_many :children, class_name:  'User', :foreign_key => 'new_user_id'
  has_many :employers, class_name:  'User', :foreign_key => 'employers_id'

  validates :first_name_en, :first_name_ru, :last_name_en, :last_name_ru, :info_en, :info_ru, presence: true

  # accepts_nested_attributes_for :project_users, allow_destroy: true
  accepts_nested_attributes_for :user_links, allow_destroy: true

  def info
    send("info_#{I18n.locale}")
  end

  def full_name
    "#{send("first_name_#{I18n.locale}")} #{send("last_name_#{I18n.locale}")}"
  end

  def as_json(options = {})
    { full_name: full_name,
      avatar_url: avatar.url || PictureUploader.default_url,
      id: id,
      user_links: user_links.as_json}
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AdminController

  before_filter :find_user, except: [:index, :new, :create]

  def index
    respond_to do |mime|
      mime.html
      mime.json { render json: { users: User.all.as_json } }
    end
  end

  def show; end

  def new; end

  def create
    @user = User.create(user_params)
    if @user.persisted?
      redirect_to [:admin, :users]
    else
      render 'admin/users/_form'
    end
  end

  def edit; end

  def update
    if @user.update_attributes(user_params)
      redirect_to [:admin, @user]
    else
      render 'admin/users/_form'
    end
  end

  def destroy
    @user.destroy
    redirect_to [:admin, :users], alert: @user.destroyed? ? nil : 'Error!'
  end

  private

  def find_user
    @user = User.find_by(id: params[:id].to_i)
  end

  def user_params
    params.require(:user).permit(
      :email, :first_name_ru, :last_name_ru, :birthday,:gender, :avatar,
      :info_ru, :password, :password_confirmation, :avatar, :avatar_cache,
      :first_name_en, :last_name_en, :info_en,
      project_users_attributes: [:id, :project_id, :user_id, :_destroy],
      user_links_attributes: [:id, :user_id, :resource_name, :link, :_destroy]
    )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    respond_to do |mime|
      mime.html
      mime.json { render json: { users: User.order(:id).as_json } }
    end
  end

  def show
    @user = User.find_by(id: params[:id].to_i)
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/admin/users/_form.html.slim
= nested_form_for [:admin, @user||User.new], multipart: true do |f|
  = render 'shared/form_errors', form_errors: f.object

  .form-group
    = image_tag f.object.avatar.url(:thumbnail)

  .form-group.row
    .col-xs-6
      = f.hidden_field :avatar_cache
      = f.file_field :avatar

    .col-xs-6
      = f.label 'Male ?'
      = f.check_box :gender

  .form-group.row
    .col-xs-6
      = f.label :first_name_en
      = f.text_field :first_name_en, class: 'form-control'

    .col-xs-6
      = f.label :first_name_ru
      = f.text_field :first_name_ru, class: 'form-control'

  .form-group.row
    .col-xs-6
      = f.label :last_name_en
      = f.text_field :last_name_en, class: 'form-control'

    .col-xs-6
      = f.label :last_name_ru
      = f.text_field :last_name_ru, class: 'form-control'


  .form-group.row
    .col-xs-6
      = f.label :birthday
      .form-group
        = f.date_select :birthday, start_year: 1970, end_year: Date.today.year - 16, class: 'form-control'
    .col-xs-6
      = f.label :email
      = f.email_field :email, class: 'form-control'

  .form-group.row
    .col-xs-6
      = f.label :info_en
      = f.text_area :info_en, class: 'form-control tinymce'
      = tinymce_assets
      = tinymce

    .col-xs-6
      = f.label :info_ru
      = f.text_area :info_ru, class: 'form-control tinymce'
      = tinymce_assets
      = tinymce

  .form-group
    = f.label_tag 'Projects'
    = f.fields_for :project_users do |pu|
      = pu.collection_select :project_id, Project.all, :id, :name, {}, class: 'projectsList'
      = pu.link_to_remove 'Remove this project', class: 'btn btn-danger'
    = f.link_to_add 'Add a project', :project_users, class: 'btn btn-success'

  .form-group
    = f.label_tag 'User Links'
    = f.fields_for :user_links do |ul|
      = ul.label_tag 'Resource Name'
      = ul.collection_select :resource_name, UserLink::RESOURCE_NAMES, :first, :last, {}, class: 'projectsList'
      = ul.label_tag 'Link'
      = ul.text_field :link
      = ul.link_to_remove 'Remove this link', class: 'btn btn-danger'
    = f.link_to_add 'Add a link', :user_links, class: 'btn btn-success'

  = f.button type: :submit, class: 'btn btn-default'

app/views/admin/users/_user.html.slim
div.text-center data-ng-repeat="user in users"
  img.center-block src='' data-ng-src="{{ user.avatar_url }}" class="img-circle img-responsive centered fix-size"
  = link_to '{{ user.full_name }}', ng_link(edit_admin_user_path(id: '{{ user.id }}'))

app/views/admin/users/edit.html.slim
h1
 | Editing of the user: #{@user.full_name}
= render 'admin/users/form'

app/views/admin/users/index.html.slim
div data-ng-controller="usersCtrl"
  = render 'admin/users/user'

app/views/admin/users/new.html.slim
h1 New user
= render 'admin/users/form'

app/views/admin/users/show.html.slim
div User: #{@user.full_name}
div birthday: #{@user.birthday}