config/routes.rb
Rails.application.routes.draw do
  scope module: 'admin', path: '/admin', as: 'admin' do
    resources :users
    resources :projects
    resources :components
    get '', to: 'users#index'
  end

  scope '/(:locale)', locale: /en|ru/ do
    resources :users, only: [:index, :show] do
      resources :projects, only: [:index]
    end
    resources :projects, only: [:show]
    resources :comments, only: [:index, :new, :create], default: {format: :json}

    root 'users#index'
  end

  match '*path' => redirect { |p, req| req.flash[:alert] = 'Aaargh, this path is not exist'; '/' }, via: [:get, :post]
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  apply_simple_captcha message: 'is incorrect'

  validates :name, length: {mininum: 1, maximum: 127}, allow_blank: false
  validates :body, length: {mininum: 1, maximum: 1024}, allow_blank: false

end

app/models/component.rb
class Component < ActiveRecord::Base
  has_many :projects, through: :component_projects
  has_many :component_projects

  validates :name, presence: true, uniqueness: true
  validates :type_id, presence: true

  COMPONENT_TYPES = {
    1 => 'framework',
    2 => 'test',
    3 => 'db',
    4 => 'css',
    5 => 'cloud',
    6 => 'payment',
    7 => 'js',
    8 => 'auth',
    9 => 'worker',
    10 => 'third_party',
    11 => 'markup'
  }

  def type_name
    COMPONENT_TYPES[type_id]
  end

  def as_json(options = {})
    { id: id, name: name, type_name: type_name }
  end
end

app/models/component_project.rb
class ComponentProject < ActiveRecord::Base
  belongs_to :component
  belongs_to :project
end

app/models/image.rb
class Image < ActiveRecord::Base
  mount_uploader :path, ::PictureUploader

  belongs_to :project
end

app/models/notify.rb
class Notify < ActiveRecord::Base
  belongs_to :notifiable, polymorphic: true
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :components, through: :component_projects
  has_many :component_projects, dependent: :destroy
  has_and_belongs_to_many :users
  # has_many :project_users, dependent: :destroy
  has_many :images, dependent: :destroy
  has_many :notifies, as: :notifiable

  validates :name, :info_en, :info_ru, presence: true
  validates :order_pos, presence: true, numericality: true

  accepts_nested_attributes_for :component_projects, allow_destroy: true
  accepts_nested_attributes_for :images, allow_destroy: true

  def info
    send("info_#{I18n.locale}").to_s
  end

  def as_json(options = {})
    { image_url: images.first.try(:url) || PictureUploader.default_url, id: id, name: name }
  end
end

app/models/project_user.rb
# class ProjectUser < ActiveRecord::Base
#   belongs_to :user
#   belongs_to :project
# end

app/models/referral.rb
class Referral < ActiveRecord::Base
  include Rails.application.routes.url_helpers


  belongs_to :referrer,  class_name: 'User', :foreign_key => 'user_id'
  belongs_to :referred,  class_name: 'User', :foreign_key => 'new_user_id'

end

app/models/user.rb
class User < ActiveRecord::Base
  mount_uploader :avatar, ::PictureUploader

  has_and_belongs_to_many :projects#, through: :project_users
  # has_many :project_users, dependent: :destroy
  has_many :user_links, dependent: :destroy
  has_many :notifies, as: :notifiable

  has_many :children, class_name:  'User', :foreign_key => 'new_user_id'
  has_many :employers, class_name:  'User', :foreign_key => 'employers_id'

  validates :first_name_en, :first_name_ru, :last_name_en, :last_name_ru, :info_en, :info_ru, presence: true

  # accepts_nested_attributes_for :project_users, allow_destroy: true
  accepts_nested_attributes_for :user_links, allow_destroy: true

  def info
    send("info_#{I18n.locale}")
  end

  def full_name
    "#{send("first_name_#{I18n.locale}")} #{send("last_name_#{I18n.locale}")}"
  end

  def as_json(options = {})
    { full_name: full_name,
      avatar_url: avatar.url || PictureUploader.default_url,
      id: id,
      user_links: user_links.as_json}
  end
end

app/models/user_link.rb
class UserLink < ActiveRecord::Base
  RESOURCE_NAMES = {
      (GIT = 0) => 'github',
      (LINKEDIN = 1) => 'linkedin',
  }.freeze

  belongs_to :user
 def as_json(options = {})
   { id: id,
     user_id: user_id,
     resource_name: RESOURCE_NAMES[resource_name],
     link: link,
     created_at: created_at,
     updated_at: updated_at
   }
 end
end

app/controllers/admin/admin_controller.rb
# http://startbootstrap.com/template-overviews/sb-admin-2/

class Admin::AdminController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  layout 'admin'

  http_basic_authenticate_with name: ENV['LOGIN'], password: ENV['PASS']
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  prepend_before_filter -> {I18n.locale = params[:locale] if params[:locale].present?}

protected
  def default_url_options
    { locale: I18n.locale }
  end

  def pagination(objs, page, pre_count = 2)
    if objs.is_a? Array
      Kaminari.paginate_array(objs).page(page.to_i).per(pre_count)
    else
      objs.page(page.to_i).per(pre_count)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  include SimpleCaptcha::ControllerHelpers
  include SimpleCaptcha::ViewHelper
  include ActionView::Helpers::FormHelper

  def index
    # @comments = pagination(Comment.order('created_at DESC'), params[:page], 15)
    respond_to do |mime|
      mime.html
      mime.json { render json: {Count: Comment.count, Items: pagination(Comment, params[:page], 5).as_json}}
    end
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.save_with_captcha
    #deliver_now!
    NotifyMailer.comment_notify(@comment).deliver_later unless (has_errors = @comment.errors.present?)

    render json:  {
      errors: @comment.errors,
      comment_id: @comment.id,
      captcha: generate_simple_captcha_image(object: 'comment')
    }, status: has_errors ? 406 :200
  end

  private

  def comment_params
    params.require(:comment).permit(:name, :email, :body, :captcha, :captcha_key)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :find_user, only: :index

  def index
    @projects = pagination(@user.projects.order(:order_pos), params[:page])
  end

  def show
    @project = Project.find_by(id: params[:id].to_i)
    @components = @project.components.group_by(&:type_name)
  end

  private

  def find_user
    redirect_to :root unless (@user = User.find_by(id: params[:user_id].to_i))
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    respond_to do |mime|
      mime.html
      mime.json { render json: { users: User.order(:id).as_json } }
    end
  end

  def show
    @user = User.find_by(id: params[:id].to_i)
  end
end

app/helpers/admin/admin_helper.rb
module Admin::AdminHelper
  def ng_link(link)
    URI::decode_www_form_component link
  end
end

app/helpers/admin/projects_helper.rb
module Admin::ProjectsHelper

end

app/helpers/application_helper.rb
module ApplicationHelper
  def lang_option(lang_name)
    exp = /\/en(\/|$)|\/ru(\/|$)/

    lang_url = if (request.path =~ exp)
      request.path.gsub(exp, "/#{lang_name}/")
    else
      uri = URI.parse(request.path)
      uri.query = Rack::Utils.parse_nested_query(uri.query).merge('locale' =>  lang_name).to_query
      uri.to_s
    end

    link_to(lang_url) do
      content_tag(:div, '&nbsp;', class: "flag #{lang_name.to_sym}_flag #{'selected' if I18n.locale == lang_name.to_sym}")
    end.html_safe
  end

  def ng_link(link)
    URI::decode_www_form_component link
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/admin/_navbar.html.slim
nav.navbar.navbar-default.navbar-static-top role="navigation" style=("margin-bottom: 0")
  .navbar-header
    button.navbar-toggle data-target=".navbar-collapse" data-toggle="collapse" type="button"
      span.sr-only Toggle navigation
      span.icon-bar
      span.icon-bar
      span.icon-bar
    a.navbar-brand href="#" Administration
  /! /.navbar-header
  ul.nav.navbar-top-links.navbar-right
    li.dropdown
      a.dropdown-toggle data-toggle="dropdown" href="#"
        i.fa.fa-envelope.fa-fw
        i.fa.fa-caret-down
      ul.dropdown-menu.dropdown-messages
        li
          a href="#"
          div
            strong John Smith
            span.pull-right.text-muted
              em Yesterday
          div Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...
        li.divider
        li
          a href="#"
          div
            strong John Smith
            span.pull-right.text-muted
              em Yesterday
          div Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...
        li.divider
        li
          a href="#"
          div
            strong John Smith
            span.pull-right.text-muted
              em Yesterday
          div Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...
        li.divider
        li
          a.text-center href="#"
            strong Read All Messages
            i.fa.fa-angle-right
    /! /.dropdown-messages
    /! /.dropdown
    li.dropdown
      a.dropdown-toggle data-toggle="dropdown" href="#"
        i.fa.fa-tasks.fa-fw
        i.fa.fa-caret-down
      ul.dropdown-menu.dropdown-tasks
        li
          a href="#"
          div
            p
              strong Task 1
              span.pull-right.text-muted 40% Complete
            .progress.progress-striped.active
              .progress-bar.progress-bar-success aria-valuemax="100" aria-valuemin="0" aria-valuenow="40" role="progressbar" style=("width: 40%")
                span.sr-only 40% Complete (success)
        li.divider
        li
          a href="#"
          div
            p
              strong Task 2
              span.pull-right.text-muted 20% Complete
            .progress.progress-striped.active
              .progress-bar.progress-bar-info aria-valuemax="100" aria-valuemin="0" aria-valuenow="20" role="progressbar" style=("width: 20%")
                span.sr-only 20% Complete
        li.divider
        li
          a href="#"
          div
            p
              strong Task 3
              span.pull-right.text-muted 60% Complete
            .progress.progress-striped.active
              .progress-bar.progress-bar-warning aria-valuemax="100" aria-valuemin="0" aria-valuenow="60" role="progressbar" style=("width: 60%")
                span.sr-only 60% Complete (warning)
        li.divider
        li
          a href="#"
          div
            p
              strong Task 4
              span.pull-right.text-muted 80% Complete
            .progress.progress-striped.active
              .progress-bar.progress-bar-danger aria-valuemax="100" aria-valuemin="0" aria-valuenow="80" role="progressbar" style=("width: 80%")
                span.sr-only 80% Complete (danger)
        li.divider
        li
          a.text-center href="#"
            strong See All Tasks
            i.fa.fa-angle-right
    /! /.dropdown-tasks
    /! /.dropdown
    li.dropdown
      a.dropdown-toggle data-toggle="dropdown" href="#"
        i.fa.fa-bell.fa-fw
        i.fa.fa-caret-down
      ul.dropdown-menu.dropdown-alerts
        li
          a href="#"
          div
            i.fa.fa-comment.fa-fw
            | New Comment
            span.pull-right.text-muted.small 4 minutes ago
        li.divider
        li
          a href="#"
          div
            i.fa.fa-twitter.fa-fw
            | 3 New Followers
            span.pull-right.text-muted.small 12 minutes ago
        li.divider
        li
          a href="#"
          div
            i.fa.fa-envelope.fa-fw
            | Message Sent
            span.pull-right.text-muted.small 4 minutes ago
        li.divider
        li
          a href="#"
          div
            i.fa.fa-tasks.fa-fw
            | New Task
            span.pull-right.text-muted.small 4 minutes ago
        li.divider
        li
          a href="#"
          div
            i.fa.fa-upload.fa-fw
            | Server Rebooted
            span.pull-right.text-muted.small 4 minutes ago
        li.divider
        li
          a.text-center href="#"
            strong See All Alerts
            i.fa.fa-angle-right
    /! /.dropdown-alerts
    /! /.dropdown
    li.dropdown
      a.dropdown-toggle data-toggle="dropdown" href="#"
        i.fa.fa-user.fa-fw
        i.fa.fa-caret-down
      ul.dropdown-menu.dropdown-user
        li
          a href="#"
            i.fa.fa-user.fa-fw
            | User Profile
        li
          a href="#"
            i.fa.fa-gear.fa-fw
            | Settings
        li.divider
        li
          a href="login.html"
            i.fa.fa-sign-out.fa-fw
            | Logout
  /! /.dropdown-user
  /! /.dropdown
  /! /.navbar-top-links
  = render 'layouts/admin/sidebar'

app/views/layouts/admin/_sidebar.html.slim
.navbar-default.sidebar role="navigation"
  .sidebar-nav.navbar-collapse
    ul#side-menu.nav
      li.sidebar-search
        .input-group.custom-search-form
          input.form-control placeholder="Search..." type="text" /
          span.input-group-btn
            button.btn.btn-default type="button"
              i.fa.fa-search
      /! /input-group
      /li
      /  a href="index.html"
      /    i.fa.fa-dashboard.fa-fw
      /    | Dashboard
      li.parted
        .row.clear
          .col-md-9
            = link_to [:admin, :users] do
              i.fa.fa-bar-chart-o.fa-fw
              | Users

          .col-md-3
            = link_to [:new, :admin, :user] do
              i.fa.fa-plus

          /span.fa.arrow
        /ul.nav.nav-second-level
        /  li
        /    a href="flot.html"  Flot Charts
        /  li
        /    a href="morris.html"  Morris.js Charts
      /! /.nav-second-level

      li.parted
        .row.clear
          .col-md-9
            = link_to [:admin, :projects] do
              i.fa.fa-bar-chart-o.fa-fw
              | Projects

          .col-md-3
            = link_to [:new, :admin, :project] do
              i.fa.fa-plus

      li
        =link_to [:admin, :components] do
          i.fa.fa-bar-chart-o.fa-fw
          | Components
      /li
      /  a href="tables.html"
      /    i.fa.fa-table.fa-fw
      /    | Tables
      /li
      /  a href="forms.html"
      /    i.fa.fa-edit.fa-fw
      /    | Forms
      /li
      /  a href="#"
      /    i.fa.fa-wrench.fa-fw
      /    | UI Elements
      /    span.fa.arrow
      /  ul.nav.nav-second-level
      /    li
      /      a href="panels-wells.html"  Panels and Wells
      /    li
      /      a href="buttons.html"  Buttons
      /    li
      /      a href="notifications.html"  Notifications
      /    li
      /      a href="typography.html"  Typography
      /    li
      /      a href="icons.html"  Icons
      /    li
      /      a href="grid.html"  Grid
      //! /.nav-second-level
      /li
      /  a href="#"
      /    i.fa.fa-sitemap.fa-fw
      /    | Multi-Level Dropdown
      /    span.fa.arrow
      /  ul.nav.nav-second-level
      /    li
      /      a href="#"  Second Level Item
      /    li
      /      a href="#"  Second Level Item
      /    li
      /      a href="#"
      /        | Third Level
      /        span.fa.arrow
      /      ul.nav.nav-third-level
      /        li
      /          a href="#"  Third Level Item
      /        li
      /          a href="#"  Third Level Item
      /        li
      /          a href="#"  Third Level Item
      /        li
      /          a href="#"  Third Level Item
      //! /.nav-third-level
      //! /.nav-second-level
      /li
      /  a href="#"
      /    i.fa.fa-files-o.fa-fw
      /    | Sample Pages
      /    span.fa.arrow
      /  ul.nav.nav-second-level
      /    li
      /      a href="blank.html"  Blank Page
      /    li
      /      a href="login.html"  Login Page

app/views/layouts/application.html.slim
doctype html
html
  head
    title JK TEAM
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    = favicon_link_tag 'favicon.ico'

    meta content="width=device-width, initial-scale=1" name="viewport"
  body class=params['controller'] ng-app="application"
    javascript:
      window.locale = "#{I18n.locale}";

    /! Navigation
    nav.navbar.navbar-inverse.navbar-fixed-top role="navigation"
      .container
        /! Brand and toggle get grouped for better mobile display
        .navbar-header
          button.navbar-toggle data-target="#collapsed-menu" data-toggle="collapse" type="button"
            span.sr-only Toggle navigation
            span.icon-bar
            span.icon-bar
            span.icon-bar
          = link_to t('brand_title'), root_path, class: 'navbar-brand'

        #collapsed-menu.collapse.navbar-collapse
          ul class='nav navbar-nav flags'
            li
              = lang_option('en')
              = lang_option('ru')

          ul class="nav navbar-nav navbar-right"
            li= link_to t('guestbook'), comments_path

        /! Collect the nav links, forms, and other content for toggling
        /#bs-example-navbar-collapse-1.collapse.navbar-collapse
        /  ul.nav.navbar-nav
        /    li
        /      a href="#"  About
        /    li
        /      a href="#"  Services
        /    li
        /      a href="#"  Contact
      /! /.navbar-collapse
      /! /.container
      /! Image Background Page Header
      /! Note: The background image is set within the business-casual.css file.
    .content
      = yield

    /! Footer
    footer.footer
      .row.vertical-align
        .col-xs-6.text-center.pad
          p
            abbr title=t('users.contact_us.email')
              span.email_text
                = t('users.contact_us.email')
                | :&nbsp;
              a href="mailto:#{ENV['GMAIL_USERNAME']}"
                = ENV['GMAIL_USERNAME']
            br
            == "#{t('copyright')} &copy; 2015"
        .col-xs-6.text-center.pad.powered_by
          = image_tag 'pow_ror.gif', height: 32
          |&nbsp;&nbsp;&shy;
          = image_tag 'pow_angularjs.gif', height: 32

    = javascript_include_tag 'angular/application', cache: true

app/views/shared/_form_errors.html.slim
- if form_errors.errors.any?
  #error_explanation
    h2= "Some errors prohibited this #{form_errors.class.name} object from being action finished successfully:"
    ul
      - form_errors.errors.messages.each_pair do |k, v|
        - name = k.to_s.split('.').last
        - v.each do |err|
          li= "#{name}: #{err}"

app/views/shared/_gallery.html.slim
#links
  = render layout: 'shared/slider' do
    - images.each do |img|
      = render layout: 'shared/slider_item' do
        = link_to img.path.url, data: {gallery: ''} do
          = image_tag img.path.standard.url, height: 150

#blueimp-gallery.blueimp-gallery
  .slides
  h3.title
  a.prev ‹
  a.next ›
  a.close ×
  a.play-pause
  ol.indicator
  /! The modal dialog, which will be used to wrap the lightbox content
  .modal.fade
    .modal-dialog
      .modal-content
        .modal-header
          button.close aria-hidden="true" type="button"  &times;
          h4.modal-title
        .modal-body.next
        .modal-footer
          button.btn.btn-default.pull-left.prev type="button"
            i.fa.fa-chevron-left
            | &nbsp;Previous
          button.btn.btn-primary.next type="button"
            | Next&nbsp;
            i.fa.fa-chevron-right

app/views/shared/_modal.html.slim
.modal.fade aria-labelledby="myModalLabel" role="dialog" tabindex="-1" id=modal_id
  .modal-dialog role="document"
    .modal-content
      .modal-header
        button.close aria-label="Close" data-dismiss="modal" type="button"
          span aria-hidden="true" &times;
        h4#myModalLabel.modal-title= title
      .modal-body
        = yield


        

app/views/shared/_slider.html.slim
/div.Wallop
/  div.Wallop-list
/    = yield
/
/  button class="Wallop-buttonPrevious" &lsaquo;
/  button class="Wallop-buttonNext" &rsaquo;

div.owl-carousel
  = yield

app/views/shared/_slider_item.html.slim
/div.Wallop-item
/  = yield
div.item
  =yield

app/views/simple_captcha/_simple_captcha.erb
<style type="text/CSS">
  .simple_captcha{border: 1px solid #ccc; padding: 5px !important;}
  .simple_captcha,
  .simple_captcha div{display: table;}
  .simple_captcha .simple_captcha_field,
  .simple_captcha .simple_captcha_image{
    border: 1px solid #ccc;
    margin: 0px 0px 2px 0px !important;
    padding: 0px !important;
  }
  .simple_captcha .simple_captcha_image img{
    margin: 0px !important;
    padding: 0px !important;
    width: 110px !important;
  }
  .simple_captcha .simple_captcha_label{font-size: 12px;}
  .simple_captcha .simple_captcha_field input{
    width: 150px !important;
    font-size: 16px;
    border: none;
    background-color: #efefef;
  }
</style>

<div class='simple_captcha'>
  <div class='simple_captcha_image'>
    <%= simple_captcha_options[:image] %>
  </div>
  
  <div class='simple_captcha_field'>
    <%= simple_captcha_options[:field] %>
  </div>
  
  <div class='simple_captcha_label'>
    <%= simple_captcha_options[:label] %>
  </div>
</div>